jobs:
  - job: ${{ parameters.name }}
    displayName: "TESTEA"
    steps:
    - script: echo "npm install"
      displayName: 'Npm install'
    - script: |
        echo "teste"
      displayName: 'Deploy'
