# MAIN TEMPLATE
stages:
- stage: "INIT"
  displayName: "Init a"
  jobs:
  - job: "JOB_A"
    displayName: "Job a"
    steps:
    - script: echo "npm install"
      displayName: 'Npm install'

    - script: |
        echo "teste"
      displayName: 'Deploy'
- stage: "TESTE"
  displayName: "Teste a"
  jobs:
  - job: "JOB_B"
    displayName: "Job a"
    steps:
    - script: echo "npm install"
      displayName: 'Npm install'

    - script: |
        echo "teste"
      displayName: 'Deploy'

- stage: "REVIEW"
  displayName: "Review a"
  jobs:
  - job: "JOB_B"
    displayName: "Job a"
    steps:
    - script: echo "npm install"
      displayName: 'Npm install'

    - script: |
        echo "teste"
      displayName: 'Deploy'
      
- stage: "TESTE2"
  displayName: "Review a"
  jobs:
  - job: "JOB_B"
    displayName: "Job a"
    steps:
    - script: echo "npm install"
      displayName: 'Npm install'

    - script: |
        echo "teste"
      displayName: 'Deploy'
