# MAIN TEMPLATE
stages:
- template: /stage-init.yml
  parameters: 
    name: $(tribe)
    jobs:
      - template: jobs_init.yml
        parameters: 
          name: "A"
      - template: jobs_init.yml
        parameters: 
          name: "B"
      - template: jobs_init.yml
        parameters: 
          name: "C"
- template: /stage-init.yml
  parameters: 
    name: "INIT2"
    jobs:
      - template: jobs_init.yml
- template: /stage-init.yml
  parameters: 
    name: "INIT3"
    jobs:
      - template: jobs_init.yml
        parameters: 
          name: "D"
      - template: jobs_init.yml
        parameters: 
          name: "E"
- template: /stage-init.yml
  parameters: 
    name: "INIT4"
    jobs:
      - template: jobs_init.yml
        parameters: 
          name: "Y"
